apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: worker
data:
  sasl: "cGxhaW50ZXh0"
  tls: "ZW5hYmxl"
  username: "JENvbm5lY3Rpb25TdHJpbmc="
  EventHubs__ConnectionString: <EVENT HUBS CONNECTION STRING EM BASE 64>
  EventHubs__BootstrapServers: <EVENT HUBS HOST COM A PORTA 9093 EM BASE 64>
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deployment
  template:
    metadata:
      labels:
        app: worker-deployment
    spec:
      containers:
        - name: worker
          image: josofd/event-driven-with-keda-event-hubs-confluent-kafka-library
          imagePullPolicy: Always
          env:
          - name: EventHubs__ConnectionString
            valueFrom:
              secretKeyRef:
                name: keda-kafka-secrets
                key: EventHubs__ConnectionString
          - name: EventHubs__BootstrapServers
            valueFrom:
              secretKeyRef:
                name: keda-kafka-secrets
                key: EventHubs__BootstrapServers
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: worker
spec:
  secretTargetRef:
  - parameter: sasl
    name: keda-kafka-secrets
    key: sasl
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: EventHubs__ConnectionString
  - parameter: tls
    name: keda-kafka-secrets
    key: tls
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaled-object
  namespace: worker
spec:
  scaleTargetRef:
    name: worker-deployment
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: <EVENT HUB NAME>.servicebus.windows.net:9093
      consumerGroup: $Default
      topic: keda-worker
      lagThreshold: "64"
      offsetResetPolicy: latest
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
